### ISSUE TITLE
Permite crear un Artista sin que se coloque información de canción Favorita

### ISSUE THREAD

**Issue by alexyirsa** [ACardenasJ/DesarrolloMovilMISO#100]
Al ingresar a la pantalla de creación de Artista y al dar click en el botón de crear dejando el campo Canción Favorita y los demás llenos, me permite crear al Artista

Pasos para reproducir:
Dar click en el ícono de la aplicación
Dar click en inicio de sesión
ingresar usuario y contraseña válidos
click en botón ingresar
click en icono de hamburguesa
click en la opción de Artista
click en el más
Diligenciar campos, dejando el de canción favorita vacío.
Dar click en crear

Resultado:
Se evidencia que la creación de Artista se realiza de forma exitosa.

Evidencias:
<img width="411" alt="Captura de Pantalla 2022-11-06 a la(s) 12 12 01 a  m" src="https://user-images.githubusercontent.com/99101760/200155403-e89dc833-f85a-44e1-920f-f9589498664f.png">

**Comment by ACardenasJ** [comment]
Se agrego una validacion para este tema
