### ISSUE TITLE
Permite crear un Artista sin que tenga un Genero asociado

### ISSUE THREAD

**Issue by alexyirsa** [ACardenasJ/DesarrolloMovilMISO#101]
Al ingresar a la pantalla de creación de Artista y al dar click en el botón de crear dejando el campo Genero y los demás llenos, me permite crear al Artista

Pasos para reproducir:
Dar click en el ícono de la aplicación
Dar click en inicio de sesión
ingresar usuario y contraseña válidos
click en botón ingresar
click en icono de hamburguesa
click en la opción de Artista
click en el más
Diligenciar campos, dejando el de Genero vacío.
Dar click en crear

Resultado:
Se evidencia que la creación de Artista se realiza de forma exitosa.

Evidencias:
<img width="405" alt="Captura de Pantalla 2022-11-06 a la(s) 12 20 51 a  m" src="https://user-images.githubusercontent.com/99101760/200155572-70a7b52d-62a9-4431-abb3-31765f875026.png">

**Comment by ACardenasJ** [comment]
Se le dio solucion poniendo una validacion y un combo box
