### ISSUE TITLE
Los campos no aceptan tildes

### ISSUE THREAD

**Issue by alexyirsa** [ACardenasJ/DesarrolloMovilMISO#93]
Al ingresar información en alguno de os campos de la aplicación se evidencia que no se estan aceptando tildes en los campos.

Pasos para reproducir:

1. Dar click en el icóno de la aplicación
2. Dar click en inicio de sesión
3. ingresar usuario y contraseña válidos
4. click en botón ingresar 
5. click en icono de hamburguesa
6. click en la opción de Álbumes 
7. click en el más
8. ingresar datos válidos para cada uno de los campos.
9. En uno de los campos ingresar información que contenga tilde.

Evidencias:

<img width="416" alt="Captura de Pantalla 2022-11-05 a la(s) 10 32 45 p  m" src="https://user-images.githubusercontent.com/99101760/200152855-f08cdba8-6933-472c-b249-b72645613185.png">

**Comment by ACardenasJ** [comment]
Este problema solo sucede en el emulador....
