### ISSUE TITLE
No permite ingresar la letra "ñ" en los campos

### ISSUE THREAD

**Issue by alexyirsa** [ACardenasJ/DesarrolloMovilMISO#94]
Al ingresar información en alguno de los campos de la aplicación se evidencia que no se estan aceptando la Ñ en los campos.

Pasos para reproducir:

Dar click en el icóno de la aplicación
Dar click en inicio de sesión
ingresar usuario y contraseña válidos
click en botón ingresar
click en icono de hamburguesa
click en la opción de Álbumes
click en el más
ingresar datos válidos para cada uno de los campos.
En uno de los campos ingresar información que contenga la letra Ñ. Para este caso se trató de colocar "año" en el campo descripción pero no fue aceptado.

Evidencias:
<img width="405" alt="Captura de Pantalla 2022-11-05 a la(s) 10 46 56 p  m" src="https://user-images.githubusercontent.com/99101760/200153102-dfaf727b-d155-49bd-bcf2-c28558c45c05.png">

**Comment by ACardenasJ** [comment]
Este problema solo sucede en el emulador
