### ISSUE TITLE
Al tratar de crear un registro duplicado para Album, el mensaje que se muestra no es claro al usuario

### ISSUE THREAD

**Issue by alexyirsa** [ACardenasJ/DesarrolloMovilMISO#96]
Al ingresar información en todos los campos, dejando el de Artista vacío, y la misma información de un registro ya existente, se presenta un mensaje de error que no es claro al usuario.

Pasos para reproducir:
Dar click en el icóno de la aplicación
Dar click en inicio de sesión
ingresar usuario y contraseña válidos
click en botón ingresar
click en icono de hamburguesa
click en la opción de Álbumes
click en el más
ingresar datos válidos para cada uno de los campos.
En el campo de Artista se debe dejar el campo vacío.
dar click en el botón crear.

Resultado:
Se evidencia que se muestra un mensaje de error que no le indica al usuario cual fue el fallo.

Evidencias:
<img width="454" alt="Captura de Pantalla 2022-11-05 a la(s) 10 58 59 p  m" src="https://user-images.githubusercontent.com/99101760/200153713-b02b18ed-8355-4522-a7ca-d7bd5559901e.png">

**Comment by ACardenasJ** [comment]
Se soluciono agregando ComboBox
