### ISSUE TITLE
No se esta validando el campo de canción favorita, cuando esta vacío

### ISSUE THREAD

**Issue by alexyirsa** [ACardenasJ/DesarrolloMovilMISO#97]
Al ingresar información en todos los campos, dejando el de Canción Favorita vacío, se evidencia que no se valida el campo y se permite la creación del registro sin dicho campo.

Pasos para reproducir:
Dar click en el icóno de la aplicación
Dar click en inicio de sesión
ingresar usuario y contraseña válidos
click en botón ingresar
click en icono de hamburguesa
click en la opción de Álbumes
click en el más
ingresar datos válidos para cada uno de los campos.
En el campo de canción Favorita se debe dejar el campo vacío.
dar click en el botón crear.

Resultado:
Se evidencia que se muestra el mensaje de album creado.

Evidencias:
<img width="410" alt="Captura de Pantalla 2022-11-05 a la(s) 11 19 41 p  m" src="https://user-images.githubusercontent.com/99101760/200154141-943842fc-b062-4031-b62d-7d37d9260eab.png">

**Comment by ACardenasJ** [comment]
Se quito campo inncesario
