### ISSUE TITLE
El texto por Default tiene errores ortográficos

### ISSUE THREAD

**Issue by alexyirsa** [ACardenasJ/DesarrolloMovilMISO#98]
Al ingresar a la pantalla de creación de Artista, se evidencia que los textos por default tienen errores de escritura y tildes.

Pasos para reproducir:
Dar click en el icóno de la aplicación
Dar click en inicio de sesión
ingresar usuario y contraseña válidos
click en botón ingresar
click en icono de hamburguesa
click en la opción de Artista
click en el más

Resultado:
Se evidencia que los textos por defecto dicen "Introducit" en vez de "Introducir. También al texto "aqui" le falta la tilde "aquí"

Evidencias:
<img width="403" alt="Captura de Pantalla 2022-11-05 a la(s) 11 53 32 p  m" src="https://user-images.githubusercontent.com/99101760/200154912-8f692ef0-4d49-4948-81dc-c93840498779.png">

**Comment by ACardenasJ** [comment]
Se corrije el error Ortografico
